trigger:
  tags:
    include:
      - '*'  # Only runs when a tag is pushed

pr:
  none  # prevents automatic runs for PRs

# deployment tokens are stored in the variable group pacman-vars
variables:
- group: pacman-vars

- name: MY_APP_LOCATION
  value: "/"  # the app's source files are in the root

- name: MY_API_LOCATION
  value: ""  # no api used

- name: MY_APP_ARTIFACT_LOCATION
  value: "/"  # output artifacts will be placed in the root

stages:
- stage: BuildAndDeploy
  displayName: "Build and Deploy"
  jobs:
  - job: BuildDeploy
    displayName: "Build and Deploy Job"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      submodules: true

    # set the correct deployment token based on the tag or branch
    - bash: |
         echo "Current tag: $(Build.SourceBranch)"
         if [ "$(Build.SourceBranch)" = "refs/tags/team1" ]; then
           echo "Using token for team1"
           echo "##vso[task.setvariable variable=AZURE_TOKEN]$(AZURE_STATIC_WEB_APPS_API_TOKEN_TEAM1)"
         elif [ "$(Build.SourceBranch)" = "refs/tags/team2" ]; then
           echo "Using token for team2"
           echo "##vso[task.setvariable variable=AZURE_TOKEN]$(AZURE_STATIC_WEB_APPS_API_TOKEN_TEAM2)"
         elif [ "$(Build.SourceBranch)" = "refs/tags/team3" ]; then
           echo "Using token for team3"
           echo "##vso[task.setvariable variable=AZURE_TOKEN]$(AZURE_STATIC_WEB_APPS_API_TOKEN_TEAM3)"
         elif [ "$(Build.SourceBranch)" = "refs/tags/team4" ]; then
           echo "Using token for team4"
           echo "##vso[task.setvariable variable=AZURE_TOKEN]$(AZURE_STATIC_WEB_APPS_API_TOKEN_TEAM4)"
         else
           echo "Tag not recognized. Token not set."
         fi
      displayName: "Set deployment token dynamically"

    # deploy to azure static web apps using the dynamically set token
    - task: AzureStaticWebApp@0
      displayName: "Deploy to Azure Static Web Apps"
      inputs:
        app_location: '$(MY_APP_LOCATION)'
        api_location: '$(MY_API_LOCATION)'
        output_location: '$(MY_APP_ARTIFACT_LOCATION)'
        azure_static_web_apps_api_token: '$(AZURE_TOKEN)'
