# triggering the pipeline on changes to the team1 branch
trigger:
- team1

pr:
- team1  # the pipeline is triggered for PRs that are targeted at the team1 branch

# deployment tokens are stored in the variable group
variables:
- group: pacman-vars
  
- name: MY_APP_LOCATION
  value: "/"  # the app's source files are in the root directory

- name: MY_API_LOCATION  
  value: ""  #  no api's used

- name: MY_APP_ARTIFACT_LOCATION
  value: "/"  # output artifacts will be placed in the root directory

# stages are used to divide the pipeline into distinct phases
stages:
- stage: BuildAndDeploy  # this stage will handle both build and deployment tasks
  displayName: "Build and Deploy"
  
  # jobs are the units of work that run inside a stage
  jobs:
  - job: BuildDeploy
    displayName: "Build and Deploy Job"
    
    # the pool is the environment where the job will run
    pool:
      vmImage: 'ubuntu-latest'  # the job is run on the latest ubuntu virtual machine

    steps:
    - checkout: self  # checks out the repo so the pipeline can access its files
      submodules: true

    # task that handles deployment to azure static web apps
    - task: AzureStaticWebApp@0  # deploys static web applications to azure
      displayName: "Deploy to Azure Static Web Apps"
      
      inputs:
        app_location: '$(MY_APP_LOCATION)'  # root (/)
        api_location: '$(MY_API_LOCATION)'  # no api used
        output_location: '$(MY_APP_ARTIFACT_LOCATION)'  # root
        azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN_TEAM1)'  # the deployment token needed to deploy
