name: Deploy web app to Azure Static Web Apps

on:
  push:
    tags:
      - '*'  # triggers only when a tag is pushed

env:
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD }}

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.MY_GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          app_artifact_location: "/"
