name: Pacman Deployment - Team1

on:
  push:
    branches:
      - team1
    paths:
      - './**'

jobs:
  deploy:
    runs-on:
      - self-hosted
      - pacman-dev-gcp-team1 # corrected placement of label

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: team1

      - name: Navigate to pacman directory and pull changes
        run: |
          cd pacman
          git pull origin team1
